language: python

env:
    global:
        - DEPENDS="numpy"

python:
    - 2.6
    - 3.2
    - 3.3
    - 3.4

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=1
    # Absolute minimum dependencies
    - python: 2.7
      env:
        - DEPENDS="numpy==1.5.1"

before_install:
    - virtualenv venv
    - source venv/bin/activate
    - pip install nose # always
    - pip install --no-index -f http://travis-wheels.scikit-image.org $DEPENDS
    - if [ "${COVERAGE}" == "1" ]; then
      pip install coverage;
      pip install coveralls;
      fi

install:
    - python setup.py install

script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - if [ "${COVERAGE}" == "1" ]; then
      cp ../.coveragerc .;
      COVER_ARGS="--with-coverage --cover-package nibabel";
      fi
    - nosetests --with-doctest $COVER_ARGS nibabel

after_success:
    - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
